on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkov Github Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: terraform/
          check: aws
          framework: terraform 
